# Generated by Django 5.2.1 on 2025-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('F_name', models.CharField(max_length=100, null=True)),
                ('dep_name', models.CharField(max_length=100, null=True)),
                ('Roll_number', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('marks', models.FloatField(null=True)),
            ],
        ),
    ]
