# Generated by Django 5.2.1 on 2025-08-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_principalmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('f_name', models.CharField(max_length=30, null=True)),
                ('P_number', models.IntegerField(max_length=17, null=True)),
                ('email', models.CharField()),
                ('address', models.CharField()),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
